chore: update dependencies
mattermost/react-native-turbo-log pull request #4
Opened 2024-04-04 15:42 UTC by larkox

#### Summary
Update dependencies

#### Ticket Link
NONE

2024-04-04 15:43 UTC, larkox commented
@enahum I have no permissions to add reviewers to this PR

2024-04-08 06:53 UTC, enahum requested changes

2024-04-08 06:53 UTC, enahum commented on example/ios/ReactNativeTurboLogExample.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = V9GZ4T2337;
remove

2024-04-08 06:53 UTC, enahum commented on example/ios/ReactNativeTurboLogExample.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = V9GZ4T2337;
remove

2024-04-08 06:53 UTC, enahum commented on example/ios/ReactNativeTurboLogExample.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 13.4;
this is fine but for the app it needs to go in release notes

2024-04-08 07:53 UTC, larkox commented on example/ios/ReactNativeTurboLogExample.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = V9GZ4T2337;
I thought I removed it :facepalm:

2024-04-08 10:52 UTC, enahum approved these changes

2024-04-08 10:52 UTC, enahum commented
I'll publish it shortly

2024-04-08 11:21 UTC, merged

2024-04-08 11:59 UTC, enahum commented
@larkox published